TOPDIR=..
plots:
	export PYTHONPATH="$(TOPDIR):$(PYTHONPATH)" && ./plot_schematic_sp3.py
	export PYTHONPATH="$(TOPDIR):$(PYTHONPATH)" && ./plot_schematic_sp3acc.py
	export PYTHONPATH="$(TOPDIR):$(PYTHONPATH)" && ./plot_schematic_sp5acc.py
	export PYTHONPATH="$(TOPDIR):$(PYTHONPATH)" && ./plot_sp8_acc_schematic.py
	export PYTHONPATH="$(TOPDIR):$(PYTHONPATH)" && ./plot_slope_at_mu.py
	export PYTHONPATH="$(TOPDIR):$(PYTHONPATH)" && ./plot_mu_vs_nmul.py
	export PYTHONPATH="$(TOPDIR):$(PYTHONPATH)" && ./plot_gap_vs_nmul.py
	export PYTHONPATH="$(TOPDIR):$(PYTHONPATH)" && ./plot_convergence.py
